In [1]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = a + b

print(result)

[5 7 9]


In [2]:
import numpy as np

array = np.random.rand(3, 3)

print(array)

[[0.99856186 0.17795052 0.10654493]
 [0.19721643 0.20885415 0.61124235]
 [0.99317965 0.49280983 0.66249093]]


In [4]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.dot(A, B)

print(result)

[[19 22]
 [43 50]]


In [3]:
import numpy as np

array = np.zeros((2, 3))

array += 10

print(array)

[[10. 10. 10.]
 [10. 10. 10.]]


In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

cumulative_sum = np.cumsum(arr)

print(cumulative_sum)

[ 1  3  6 10 15]


In [6]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[4, 5, 6], [7, 8, 9]])

result = b + a

print(result)

[[ 5  7  9]
 [ 8 10 12]]


In [7]:
import numpy as np

matrix = np.random.randint(1, 101, size=(4, 4))

max_value = np.max(matrix)
min_value = np.min(matrix)

print("Matrix:\n", matrix)
print("Maximum value:", max_value)
print("Minimum value:", min_value)

Matrix:
 [[31 48 16 85]
 [ 2 54 83 93]
 [22 57 13 69]
 [ 8  8 47 74]]
Maximum value: 93
Minimum value: 2


In [8]:
import numpy as np

matrix = np.eye(5)

print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

filtered_arr = arr[arr <= 5]

print(filtered_arr)

[1 2 3 4 5]


In [10]:
import numpy as np

matrix = np.random.randint(0, 11, size=(3, 3))

transpose_matrix = matrix.T

print("Matrix:\n", matrix)
print("Transpose:\n", transpose_matrix)

Matrix:
 [[6 5 0]
 [7 7 5]
 [8 1 5]]
Transpose:
 [[6 7 8]
 [5 7 1]
 [0 5 5]]
